#!/bin/bash

## Launch fail2Ban
/usr/bin/fail2ban-server

status=$?

if [ $status -ne 0 ]; then
    echo "Failed to start fail2ban: $status"
    exit $status
fi

## Launch nginx
nginx -g "daemon off;"

status=$?

if [ $status -ne 0 ]; then
    echo "Failed to start nginx: $status"
    exit $status
fi

while sleep 60; do
    ps aux | grep fail2ban | grep -q -v grep
    FAIL2BAN_STATUS=$?

    ps aux | grep nginx | grep -q -v grep
    NGINX_STATUS=$?

    if [ $FAIL2BAN_STATUS -ne 0 -o $NGINX_STATUS -ne 0 ]; then
        echo "One of the processes has already exited."
        exit 1
    fi
done
